version: 2
jobs:
  build:
    working_directory: ~/storybook-typescript-starter
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: Run build
          command: npm run build
