version: 2
jobs:
  build:
    docker:
      image: circleci/node:8.9.1
    working_directory: ./
    steps:
        - checkout
        - run:
            name: Run build
            command: npm run build
